services:
  mysql:
    image: mysql:8.0
    container_name: prisma_test_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: prisma_test
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
